Oodle/Oodle/Models/Assignment.cs
namespace Oodle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Assignment")]
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            Documents = new HashSet<Document>();
            Grades = new HashSet<Grade>();
            Questions = new HashSet<Question>();
        }

        public int AssignmentID { get; set; }

        public int ClassID { get; set; }

        [Required]
        [StringLength(128)]
        public string Name { get; set; }

        [StringLength(512)]
        public string Description { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? DueDate { get; set; }

        public virtual Class Class { get; set; }

        public int Weight { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}

Oodle/Oodle/Models/Grade.cs
namespace Oodle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Grade
    {
        [Key]
        public int GradesID { get; set; }

        public int UsersID { get; set; }

        public int AssignmentID { get; set; }

        [StringLength(64)]
        public string Grader { get; set; }

        [StringLength(256)]
        public string Comment { get; set; }

        [Column("Grade")]
        public int Grade1 { get; set; }

        public virtual Assignment Assignment { get; set; }

        public virtual User User { get; set; }
    }
}

Oodle/Oodle/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Oodle.Models;
using Oodle.Models.ViewModels;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Net;
using System.IO;
using System.Data.SqlClient;
using System.Configuration;
using System.Diagnostics;
using Oodle.Utility;
using System.Text.RegularExpressions;

namespace Oodle.Controllers
{
    [Authorize]
    public class TeachersController : Controller 
    {
        //Slack access
        private SlackManager slack = new SlackManager();

        // GET: Teachers
        private Model1 db = new Model1();

        public ActionResult test(int classID)
        {
            var idid = User.Identity.GetUserId();

            User user = db.Users.Where(a => a.IdentityID == idid).FirstOrDefault();
            UserRoleClass urc = db.UserRoleClasses.Where(s => s.UsersID == user.UsersID && s.ClassID == classID).FirstOrDefault();

            if (urc == null || urc.RoleID != 0)
            {
                return RedirectToAction("Index", "Class", new { classId = classID });
            }
            return null;
        }


        public ActionResult Index(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }
            var teacher = getTVM(classID);

            return View("index", "_TeacherLayout", teacher);
        }

        public ActionResult Accept(int classID, int userID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            db.UserRoleClasses.Where(i => i.UsersID == userID & i.ClassID == classID).ToList().ForEach(x => x.RoleID = 2);
            db.SaveChanges();

            //get user and class
            User user = db.Users.Where(i => i.UsersID == userID).FirstOrDefault();
            Class c = db.Classes.Where(i => i.ClassID == classID).FirstOrDefault();
            //Send request to slack for user to join the group
            //slack.JoinChannel(user.Email, c.Name);

            return RedirectToAction("Index", new { classId = classID });
        }

        public ActionResult Reject(int classID, int userID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            db.UserRoleClasses.Remove(db.UserRoleClasses.Where(i => i.UsersID == userID & i.ClassID == classID).FirstOrDefault());
            db.SaveChanges();

            return RedirectToAction("Index", new { classId = classID });
        }

        public ActionResult Edit(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            ViewBag.id = classID;

            var teacher = getTVM(classID);

            return View("Edit", "_TeacherLayout", teacher);
        }

        public ActionResult EditClass()
        {
            ViewBag.RequestMethod = "POST";

            string name = Request.Form["name"];
            string desc = Request.Form["description"];
            int classID = int.Parse(Request.Form["classID"]);

            if (test(classID) != null)
            {
                return test(classID);
            }

            db.Classes.Where(i => i.ClassID == classID).ToList().ForEach(x => x.Name = name);
            db.Classes.Where(i => i.ClassID == classID).ToList().ForEach(x => x.Description = desc);

            db.SaveChanges();

            return RedirectToAction("Index", new { classId = classID });
        }

        public ActionResult AddNotifToClass(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            ViewBag.id = classID;

            var teacher = getTVM(classID);

            return View("AddNotifToClass", "_TeacherLayout", teacher);
        }

        public ActionResult SaveNotif()
        {
            ViewBag.RequestMethod = "POST";
            string notif = Request.Form["notification"];
            int classID = int.Parse(Request.Form["classID"]);

            if (test(classID) != null)
            {
                return test(classID);
            } 

            Class hasSlack = db.Classes.Where(i => i.ClassID == classID).FirstOrDefault();


            if (!(string.IsNullOrEmpty(notif)))
            {
                if (!hasSlack.SlackName.Equals("%"))
                {
                    slack.SlackNotif(notif, hasSlack.SlackName);
                }
                AddNotification(notif, classID);
            }


            return RedirectToAction("Index", new { classId = classID });
        }

        public ActionResult RemoveNotif(int classID, int notifID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }

            ClassNotification cNotif = db.ClassNotifications.Where(n => n.ClassID == classID 
                                                                && n.ClassNotificationID == notifID).FirstOrDefault();
            if(cNotif == null)
            {
                return RedirectToAction("Index", new { classId = classID });
            }

            var teacher = getTVM(classID);
            teacher.rNotif = cNotif;

            return View("RemoveNotif", "_TeacherLayout", teacher);
        }

        public ActionResult RemoveNotification(int classID, int notifID)
        {
            
            if (test(classID) != null)
            {
                return test(classID);
            }

            ClassNotification notif = db.ClassNotifications.Where(n => n.ClassID == classID
                                                    && n.ClassNotificationID == notifID).FirstOrDefault();
            db.ClassNotifications.Remove(notif);
            db.SaveChanges();

            return RedirectToAction("Index", new { classId = classID });
        }

        private void AddNotification(string notif, int classID)
        {
            ClassNotification cNotif = new ClassNotification();
            cNotif.Notification = notif;
            cNotif.TimePosted = DateTime.Now;
            cNotif.ClassID = classID;
            db.ClassNotifications.Add(cNotif);
            db.SaveChanges();           
        }

        public ActionResult Delete(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }


            var list = db.UserRoleClasses.Where(i => i.ClassID == classID);
            Class hasSlack = db.Classes.Where(i => i.ClassID == classID).FirstOrDefault();
            foreach (var i in list)
            {
                db.UserRoleClasses.Remove(i);
            }

            //classID = 1;
            if (!hasSlack.SlackName.Equals("%"))
            {
                slack.DeleteChannel(hasSlack.SlackName);
            }

            db.Classes.Remove(db.Classes.Where(i => i.ClassID == classID).FirstOrDefault());

            db.SaveChanges();


            return RedirectToAction("List", "Class");
        }


        public ActionResult MakeGrade()
        {
            return View("MakeGrade", "_TeacherLayout");
        }

        /*
         * Method returns the ViewRoster Html object and loads in 3 db models into the view.
         * 
         */
        public ActionResult ViewRoster()
        {
            var classes = db.Classes.ToList(); // list of all classes
            var user = db.Users.ToList(); // list of all users
            var roles = db.UserRoleClasses.ToList(); // List of all Roles

            ViewBag.name = User.Identity.GetUserName(); // testing viewbag output
  
            var urcL = db.UserRoleClasses.Where(i => i.RoleID == 0);
            var list = new List<int>();
            foreach (var i in urcL)
            {
                list.Add(i.UsersID);
            }
            var request = db.Users.Where(i => list.Contains(i.UsersID)).ToList();
            var request2 = db.Users.Where(i => list.Contains(i.UsersID)).ToList();

            var teacher = new TeacherVM(classes, user, roles);  // New TeacherVM using the list of classes and user
            return View("ViewRoster", teacher);
            
        }

        public ActionResult Assignment(int classID)
        {
            var teacher = getTVM(classID);

            return View("Assignment", "_TeacherLayout", teacher);
        }


        public TeacherVM getTVM(int classID)
        {
            var urcL = db.UserRoleClasses.Where(i => i.RoleID == 3 && i.ClassID == classID);
            var list = new List<int>();

            foreach (var i in urcL)
            {
                list.Add(i.UsersID);
            }
            var request = db.Users.Where(i => list.Contains(i.UsersID)).ToList();

            var teacher = new TeacherVM(db.Classes.Where(i => i.ClassID == classID).FirstOrDefault(), request);

            teacher.assignment = db.Assignments.Where(i => i.ClassID == classID).OrderBy(i => i.StartDate).ToList();

            teacher.notifs = db.ClassNotifications.Where(i => i.ClassID == classID).OrderBy(i => i.TimePosted).ToList();

            return teacher;
        }



        public ActionResult CreateAssignmentAction()
        {
            ViewBag.RequestMethod = "POST";

            string name = Request.Form["name"];
            string desc = Request.Form["description"];
            string id = Request.Form["classID"];
            string startDate = Request.Form["startDate"];
            string dueDate = Request.Form["dueDate"];
            string weight = Request.Form["weight"];



Oodle/Oodle/Views/Teachers/AddNotifToClass.cshtml
@model Oodle.Models.ViewModels.TeacherVM

<div class="form-style-6">
    <h1>Add Notification to @Model.cl.Name</h1>

    <form method="post" action="SaveNotif">

        <input type="hidden" name="classID" value=@Model.cl.ClassID required />

        <label for="notification">Notification</label><br />
        <textarea name="notification" placeholder="Enter notification here..." value=""></textarea>


        <br />
        <input type="submit" name="submit" value="Add Notification" />

    </form>
</div>

Oodle/Oodle/Views/Teachers/Assignment.cshtml

@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "Assignment";
}
<center><h2>Assignments</h2></center>


<center>
    <a class="buttonReject" href="@Url.Action("CreateAssignment", "Teachers", new { classID = Model.cl.ClassID } )">
        Create an assignment
    </a>
</center>
<br />


<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">



            <div>
                @for (int i = 0; i < Model.assignment.Count(); i++)
                {

                    var assi = Model.assignment[i];
                    <div class="block">
                        <div class="classItem">
                            <div class="title">
                                @Html.DisplayFor(Name => assi.Name)
                            </div>
                            <div class="description">
                                @Html.DisplayFor(Desc => assi.Description)
                            </div>
                            <div class="dateLeft" style="color:#17252A">
                                Start Date: @Html.DisplayFor(Desc => assi.StartDate)
                            </div>
                            <div class="dateRight" style="color:#17252A">
                                Due Date: @Html.DisplayFor(Desc => assi.DueDate)
                            </div>
                            <a href="@Url.Action("EditAssignment", "Teachers", new { classID = Model.cl.ClassID, assignmentID = assi.AssignmentID })" class="edit">
                                Edit
                            </a>
                            <a href="@Url.Action("SubmissionView", "Teachers", new { classID = Model.cl.ClassID, assignmentID = assi.AssignmentID })" class="submissions">
                                View Submissions
                            </a>
                        </div>
                    </div>
                    <br />
                    <br />

                }
            </div>


        </div>
    </div>
</div>

Oodle/Oodle/Views/Teachers/CreateAssignment.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "CreateAssignment";
}




<div class="form-style-6">
    <form method="post" action="CreateAssignmentAction">
        <div>
            <h1>Create an Assignment</h1>

            <label for="name">Name of Assignment:</label><br />
            <input type="text" name="name" placeholder="e.g., Assignment one, history of modernism" value="" required /><br />
            <input type="hidden" name="classID" value="@Model.cl.ClassID" />

            <label for="description">Description of your Assignment:</label> <br />
            <textarea name="description" placeholder="e.g., please read chapter four and attach a word document of your answers to the questions at the end of the chapter." required></textarea>

            <label for="weight">Weight of Grade:</label> <br />
            <input type="number" name="weight" placeholder="0" value="" max="1000" min="0" required /><br />

            <br />
            <label for="startDate">Start Date</label><br />
            <input type="datetime" name="startDate" value="@DateTime.Now" required />

            <br />
            <label for="dueDate">Due Date</label><br />
            <input type="datetime" name="dueDate" value="@DateTime.Now" required />

        </div>
        <div>
            <input type="submit" name="submit" value="Create Assignment" />
        </div>
    </form>
</div>

Oodle/Oodle/Views/Teachers/CreateQuiz.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "CreateQuiz";
}
<center><h2>CreateQuiz View for Teachers Controller</h2></center>

Oodle/Oodle/Views/Teachers/CreateSlack.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "CreateSlack";
}
<center><h2>CreateSlack View for Teachers Controller</h2></center>

Oodle/Oodle/Views/Teachers/CreateTask.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "CreateTask";
}
<center><h2>CreateTask View for Teachers Controller</h2></center>

Oodle/Oodle/Views/Teachers/Edit.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "Edit";
}






<div class="form-style-6">
    <h1>Edit your class</h1>

    <form method="post" action="EditClass">


        <label for="name">Name of class:</label><br />
        <input type="text" name="name" value="@Model.cl.Name" required />
        <br />

        <input type="hidden" name="classID" value=@Model.cl.ClassID required />

        <br />



        <label for="description">Brief description of your class:</label> <br />
        <textarea name="description" placeholder="We will learn about..." value="" required>@Model.cl.Description</textarea>

     <br />
        <input type="submit" name="submit" value="Save Changes" />

    </form>
</div>


Oodle/Oodle/Views/Teachers/EditAssignment.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "EditAssignment";
}





<div class="form-style-6">
    <form method="post" action="EditAssignmentAction">
        <div>
            <h1>Edit Your Assignment</h1>
            
            <label for="name">Name</label> <br />
            <input type="text" name="name" value="@Model.assignment.FirstOrDefault().Name" required />


            <input type="hidden" name="assignmentID" value="@Model.assignment.FirstOrDefault().AssignmentID" />

            <input type="hidden" name="classID" value="@Model.cl.ClassID" />
            <br />


            <label for="description">Description</label><br />
            <textarea name="description" required>@Model.assignment.FirstOrDefault().Description</textarea><br />

            <label for="weight">Weight of Grade:</label> <br />
            <input type="number" name="weight" placeholder="0" value="@Model.assignment.FirstOrDefault().Weight" max="1000" min="0" required /><br />

            <label for="startDate">Start Date</label>             <br />

            <input type="datetime" name="startDate" value="@Model.assignment.FirstOrDefault().StartDate" required />
            <br />
            <label for="dueDate">Due Date</label>            <br />

            <input type="datetime" name="dueDate" value="@Model.assignment.FirstOrDefault().DueDate" required />

        </div>
        <div>
            <input type="submit" name="submit" value="Update Assignment" />
        </div>
    </form>
</div>




Oodle/Oodle/Views/Teachers/Grades.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "Grades";
}

<h2>Grades</h2>
<div class="slide-toggle2">
    <div>
        <br />
        <!-- fluid -->
        <div class="box-toggle">
            @if(true){
                var number = 0;

                foreach (var i in Model.users.ToList())
                {
                    <div class="contorol">

                        <h3>
                            @Html.DisplayFor(Name => i.UserName)
                        </h3>
                        <span class="toggle-info pull-left">
                            <i class="fa fa-plus"></i>
                        </span>
                    </div>
                    <div class="content-box">
                        <div class="black">
                            @for (int i2 = 0; i2 < Model.documents.Where(j => j.UserID == i.UsersID).Count(); i2++)
                            {
                                var doc = Model.documents[i2];
                                var classID = Model.cl.ClassID;
                                var documentID = doc.Id;
                                var assignmentID = doc.AssignmentID;

                                <div>@doc.Assignment.Name</div>

                                <a href="@Url.Action("Grade", "Teachers", new { classID = classID, documentID = documentID, assignmentID = assignmentID })"> Grade Assignment </a>
                                <div>
                                    Current Grade: @if (doc.Grade == -1)
                                    {
                                        <div>Not yet graded.</div>
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(Grade => doc.Grade);
                                    }
                                </div>
                                <hr />
                            }
                        </div>
                    </div>
                    <div>
                        Average on Graded Assignments Based off Weights:
                        @Model.classGrade[number]
                    </div>
                    number = number + 1;

                    <hr />
                }
            }
        </div>
    </div>
</div>
<div>

</div>
@section scripts
{
    <script type="text/javascript" src="~/Scripts/scriptone.js"></script>
}

Oodle/Oodle/Views/Teachers/Index.cshtml

@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "Index";
}

<div class="row fontClass" >

    <h3>
        Your class page for: @Html.DisplayFor(Name => Model.cl.Name)
    </h3>
    <hr class="style-four" />
    <hr class="style-four" />

    <div class="testingURL">
        <a href="@Url.Action("Edit", "Teachers", new { ClassID = (Model.cl.ClassID)} )">
            Edit Class
        </a>
        <p style="display:inline">----------------------</p>

        <a href="@Url.Action("Delete", "Teachers", new { ClassID = (Model.cl.ClassID)})">
            Delete Class
        </a>

    </div>
    <hr class="style-four" />
    <hr class="style-four" />

    <div class="container">
        <div>
            <div class="col-lg-6" id="teacherPage">
                <h3>Description</h3>
                <p style="font-size:14px;">
                    @Html.DisplayFor(Description => Model.cl.Description)
                </p>
            </div>
            <div class="col-sm-6" id="teacherPage">
                <h3> Notifications </h3>
                @foreach (var notif in Model.notifs)
                {
                <p>
                    @Html.DisplayFor(Notification => notif.Notification)
                    <a href="@Url.Action("RemoveNotif", "Teachers", new { classID = (notif.ClassID), notifID = (notif.ClassNotificationID)} )">
                        Remove Notification
                    </a>
                </p>
                }
                <a href="@Url.Action("AddNotifToClass", "Teachers", new { ClassID = (Model.cl.ClassID)} )">
                    Add A Notification
                </a>
            </div>
        </div>
    </div>
    <hr class="style-four" />
    <hr class="style-four" />


</div>



<h4>Accept or reject the following students to the class:</h4>
<div class="buttonReject">
    @for (int i = 0; i < Model.users.Count(); i++)
    {
        var user = Model.users[i];
        @Html.DisplayFor(Name => user.UserName)<p style="display:inline">:</p>
        <a href="@Url.Action("Accept", "Teachers", new { ClassID = (Model.cl.ClassID), UserID = user.UsersID }, null)">
            Accept
        </a>
        <p style="display:inline">|</p>
        <a href="@Url.Action("Reject", "Teachers", new { ClassID = (Model.cl.ClassID), UserID = user.UsersID }, null)">
            Reject
        </a>
        <br />

    }
</div>

Oodle/Oodle/Views/Teachers/MakeGrade.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "MakeGrade";
}

@using (Html.BeginForm("DownloadFile", "Students", FormMethod.Post))
{
    <input type="hidden" id="hfFileId" name="FileId" />
    <input type="submit" id="btnDownload" value="Download" style="display:none" />
}

    <div class="lb">

        <h1>@Model.assignment.FirstOrDefault().Name</h1>
        <h4>
            @Model.users.FirstOrDefault().UserName's Submission
        </h4>
        <div>
            @Model.assignment.FirstOrDefault().Description
        </div>
        <a class="btn btn-info" href="javascript:;" onclick="DownloadFile(@Model.documents.FirstOrDefault().Id)">
            Download Submission
        </a>

        <div class="form-style-6">
            <form method="post" action="SubmitGrade?classID=@Model.cl.ClassID&documentID=@Model.documents.FirstOrDefault().Id&assignmentID=@Model.assignment.FirstOrDefault().AssignmentID">
                <label for="grade">Grade: </label>
                <input type="number" name="grade" placeholder="e.g., 100" value="" required min="0" max="100"/>/100<br />
                <input type="submit" name="submit" value="Submit Grade" />
            </form>
        </div>

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script type="text/javascript">
            function DownloadFile(fileId) {
                $("#hfFileId").val(fileId);
                $("#btnDownload")[0].click();
            };
        </script>
    </div>

Oodle/Oodle/Views/Teachers/RemoveNotif.cshtml
@model Oodle.Models.ViewModels.TeacherVM


<div class="removeNotif">
    <h1>Remove Notification</h1>
    <p>Click the Remove Notification button to confirm removing, otherwise click the back button to go back to your class page</p>
    <p>Notification To Remove: @Model.rNotif.Notification</p>

    @Html.ActionLink("Back", "Index", "Teachers", new { ClassID = Model.rNotif.ClassID }, new { @class = "" })

    @Html.ActionLink("Remove Notification", "RemoveNotification", "Teachers", new { classID = Model.rNotif.ClassID, notifID = Model.rNotif.ClassNotificationID }, new { @class = "" })
    <p></p>

</div>

Oodle/Oodle/Views/Teachers/SubmissionView.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "SubmissionView";
}

<h2>Submissions</h2>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
   
</head>
@using (Html.BeginForm("DownloadFile", "Students", FormMethod.Post))
{
    <input type="hidden" id="hfFileId" name="FileId" />
    <input type="submit" id="btnDownload" value="Download" style="display:none" />
}
<hr />
<table cellpadding="0" cellspacing="0" class="responsive-table">
    <tr>
        <th style="width:50px">Student</th>
        <th style="width:120px">File Name</th>
        <th style="width:120px">Grade Link</th>
        <th style="width:80px">Download</th>
    </tr>
    @if (Model.documents.Count() > 0)
    {
        for (int i = 0; i < Model.documents.Count(); i++)
        {
            var file = Model.documents[i];
            var user = Model.users[i];
            var classID = Model.cl.ClassID;
            var documentID = Model.documents[i].Id;
            var assignmentID = Model.assignment.FirstOrDefault().AssignmentID;
            <tr>
                <td>@user.UserName</td>
                <td>@file.Name</td>
                <td><a href="@Url.Action("Grade", "Teachers", new {classID = classID,documentID = documentID,assignmentID = assignmentID})"> Grade </a></td>
                <td><a href="javascript:;" onclick="DownloadFile(@file.Id)">Download</a></td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td colspan="3">&nbsp;</td>
        </tr>
    }
</table>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    function DownloadFile(fileId) {
        $("#hfFileId").val(fileId);
        $("#btnDownload")[0].click();
    };
</script>

Oodle/Oodle/Views/Teachers/ViewRoster.cshtml
@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "ViewRoster";
}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

@section scripts
{
    <script type="text/javascript" src="~/Scripts/scriptone.js"></script>
}

    <div id="classListBody">  
        <h2 style="text-align:center;">
            Class Rosters
        </h2>
        <hr />
        <h2 style="text-align:center;">
            Classes For: @ViewBag.name
            <br />
        </h2>
    </div>

    <div>
        @foreach (var i in Model.classList)
    {

        // +Get Teacher ID
        // +Match with Class ID
        // +Print out Class
        // Print out Students that match class

        //Loops Users, Finds Teacher
        for (int u = 0; u < Model.users.Count(); u++)
        {

            // If Teach Print Class
            if (i.UsersID == Model.users[u].UsersID && Model.users[u].UserName == ViewBag.name)
            {
                <div class="slide-toggle text-center">
                    <div class="container">
                        <div class="box-toggle">
                            <div>
                                <div class="contorol">
                                    <h1>@Html.DisplayFor(Name => i.Name)</h1>
                                    <hr/>
                                    <h2>@Html.DisplayFor(Description => i.Description)</h2>
                                    <span class="toggle-info pull-left">
                                        <i class="fa fa-plus"></i>
                                    </span>
                                </div>
                                <div class="content-box">
                                    @for (int x = 0; x < Model.roles.Count(); x++)
                                    {
                                    if (Model.roles[x].ClassID == i.ClassID && Model.roles[x].RoleID == 2)
                                    {
                                        var bob = Model.roles[x].UsersID;
                                        for (int c = 0; c < Model.users.Count(); c++)
                                        {
                                            if (Model.users[c].UsersID == bob)
                                            {
                                               <h5>@Model.users[c].UserName</h5>
                                        }
                                     }
                                     }
                                     }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        }
    }
}
</div>


