Oodle/Oodle/Models/Assignment.cs
namespace Oodle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Assignment")]
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            Documents = new HashSet<Document>();
            Grades = new HashSet<Grade>();
            Questions = new HashSet<Question>();
        }

        public int AssignmentID { get; set; }

        public int ClassID { get; set; }

        [Required]
        [StringLength(128)]
        public string Name { get; set; }

        [StringLength(512)]
        public string Description { get; set; }

        public DateTime? StartDate { get; set; }

        public DateTime? DueDate { get; set; }

        public virtual Class Class { get; set; }

        public int Weight { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}

Oodle/Oodle/Models/Grade.cs
namespace Oodle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Grade
    {
        [Key]
        public int GradesID { get; set; }

        public int UsersID { get; set; }

        public int AssignmentID { get; set; }

        [StringLength(64)]
        public string Grader { get; set; }

        [StringLength(256)]
        public string Comment { get; set; }

        [Column("Grade")]
        public int Grade1 { get; set; }

        public virtual Assignment Assignment { get; set; }

        public virtual User User { get; set; }
    }
}

Oodle/Oodle/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Oodle.Models;
using Oodle.Models.ViewModels;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Net;
using System.IO;
using System.Data.SqlClient;
using System.Configuration;

namespace Oodle.Controllers
{
    [Authorize]
    public class StudentsController : Controller
    {
        private Model1 db = new Model1();

        public ActionResult test(int classID)
        {
            var idid = User.Identity.GetUserId();

            User user = db.Users.Where(a => a.IdentityID == idid).FirstOrDefault();
            UserRoleClass urc = db.UserRoleClasses.Where(s => s.UsersID == user.UsersID && s.ClassID == classID).FirstOrDefault();

            if (urc == null || urc.RoleID != 2)
            {
                return RedirectToAction("Index", "Class", new { classId = classID });
            }
            return null;
        }



        public ActionResult Index(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }

            var student = getTVM(classID);


            return View("Index", "_StudentLayout", student);
        }




        public ActionResult Grade()
        {
            return View("Grade", "_StudentLayout");
        }

        public ActionResult Assignment(int classID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }

            var student = getTVM(classID);

            return View("Assignment", "_StudentLayout", student);
        }

        public ActionResult Quiz()
        {
            return View("Quiz", "_StudentLayout");
        }

        public ActionResult Task()
        {
            return View("Task", "_StudentLayout");
        }

        public ActionResult Slack()
        {
            return View("Slack", "_StudentLayout");
        }




        public TeacherVM getTVM(int classID)
        {
            var urcL = db.UserRoleClasses.Where(i => i.RoleID == 3 && i.ClassID == classID);
            var list = new List<int>();

            foreach (var i in urcL)
            {
                list.Add(i.UsersID);
            }
            var request = db.Users.Where(i => list.Contains(i.UsersID)).ToList();

            var teacher = new TeacherVM(db.Classes.Where(i => i.ClassID == classID).FirstOrDefault(), request);

            teacher.assignment = db.Assignments.Where(i => i.ClassID == classID).OrderBy(i => i.StartDate).ToList();

            teacher.notifs = db.ClassNotifications.Where(i => i.ClassID == classID).OrderBy(i => i.TimePosted).ToList();

            return teacher;
        }





        ///////////////////////////////////////////////////////

        public ActionResult AssignmentTurnIn(int classID, int assignmentID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }

            var urcL = db.UserRoleClasses.Where(i => i.RoleID == 3 && i.ClassID == classID);
            var list = new List<int>();

            foreach (var i in urcL)
            {
                list.Add(i.UsersID);
            }
            var request = db.Users.Where(i => list.Contains(i.UsersID)).ToList();

            var student = new TeacherVM(db.Classes.Where(i => i.ClassID == classID).FirstOrDefault(), request);

            student.assignment = db.Assignments.Where(i => i.ClassID == classID && i.AssignmentID == assignmentID).ToList();

            var idid = User.Identity.GetUserId();
            int studentID = db.Users.Where(a => a.IdentityID == idid).FirstOrDefault().UsersID;

            student.documents = GetFiles(classID, assignmentID, studentID);

            return View(student);
        }

        [HttpPost]
        public ActionResult AssignmentTurnIn(HttpPostedFileBase postedFile, int classID, int assignmentID)
        {
            if (test(classID) != null)
            {
                return test(classID);
            }

            var idid = User.Identity.GetUserId();
            int studentID = db.Users.Where(a => a.IdentityID == idid).FirstOrDefault().UsersID;

            var urcL = db.UserRoleClasses.Where(i => i.RoleID == 3 && i.ClassID == classID);
            var list = new List<int>();

            foreach (var i in urcL)
            {
                list.Add(i.UsersID);
            }
            var request = db.Users.Where(i => list.Contains(i.UsersID)).ToList();

            var student = new TeacherVM(db.Classes.Where(i => i.ClassID == classID).FirstOrDefault(), request);

            student.assignment = db.Assignments.Where(i => i.ClassID == classID && i.AssignmentID == assignmentID).ToList();

            byte[] bytes;
            using (BinaryReader br = new BinaryReader(postedFile.InputStream))
            {
                bytes = br.ReadBytes(postedFile.ContentLength);
            }

            var submitted = DateTime.Now;

            string constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                string query = "INSERT INTO Documents VALUES (@Name, @ContentType, @Data, @Submitted, @ClassID, @AssignmentID, @userID, @grade)";
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    cmd.Parameters.AddWithValue("@Name", Path.GetFileName(postedFile.FileName));
                    cmd.Parameters.AddWithValue("@ContentType", postedFile.ContentType);
                    cmd.Parameters.AddWithValue("@Data", bytes);
                    cmd.Parameters.AddWithValue("@ClassID", classID);
                    cmd.Parameters.AddWithValue("@AssignmentID", assignmentID);
                    cmd.Parameters.AddWithValue("@userID", studentID);
                    cmd.Parameters.AddWithValue("@Submitted", submitted);
                    cmd.Parameters.AddWithValue("@grade", -1);

                    con.Open();
                    cmd.ExecuteNonQuery();
                    con.Close();
                }
            }

            student.documents = GetFiles(classID, assignmentID, studentID);


            return View("AssignmentTurnIn", student);
        }

        [HttpPost]
        public FileResult DownloadFile(int? fileId)
        {
            byte[] bytes;
            string fileName, contentType;
            string constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand())
                {
                    cmd.CommandText = "SELECT Name, Data, ContentType FROM Documents WHERE Id=@Id";
                    cmd.Parameters.AddWithValue("@Id", fileId);
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        sdr.Read();
                        bytes = (byte[])sdr["Data"];
                        contentType = sdr["ContentType"].ToString();
                        fileName = sdr["Name"].ToString();
                    }
                    con.Close();
                }
            }

            return File(bytes, contentType, fileName);
        }

        private static List<Document> GetFiles(int classID, int assignmentID, int studentID)
        {
            List<Document> files = new List<Document>();
            string constr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand())
                {

                    cmd.CommandText = "SELECT Id, Name FROM Documents WHERE ClassID=@classID AND AssignmentID=@assignmentID AND userID=@userID ";
                    cmd.Parameters.AddWithValue("@classID", classID);
                    cmd.Parameters.AddWithValue("@assignmentID", assignmentID);
                    cmd.Parameters.AddWithValue("@userID", studentID);
                    
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            files.Add(new Document
                            {
                                Id = Convert.ToInt32(sdr["Id"]),
                                Name = sdr["Name"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }
            return files;
        }
    }
}

Oodle/Oodle/Views/Students/Assignment.cshtml

@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "Assignment";
}
<center><h2>Assignments</h2></center>


<div>
    @for (int i = 0; i < Model.assignment.Count(); i++)
    {

        var assi = Model.assignment[i];
        <div class="block">
            <a href="@Url.Action("AssignmentTurnIn", "Students", new { ClassID = (assi.ClassID), AssignmentID = (assi.AssignmentID) })">
                <div class="classItem">
                    <div class="title">
                        @Html.DisplayFor(Name => assi.Name)
                    </div>
                    <div class="description">
                        @Html.DisplayFor(Desc => assi.Description)
                    </div>
                    <div class="dateLeft">
                        Start Date: @Html.DisplayFor(Desc => assi.StartDate)
                    </div>
                    <div class="dateRight">
                        Due Date: @Html.DisplayFor(Desc => assi.DueDate)
                    </div>
                </div>
            </a>
        </div>
        <br />
        <br />

    }
</div>

<!--, new { classID = (assi.ClassID), assignmentID = assi.AssignmentID }-->

Oodle/Oodle/Views/Students/AssignmentTurnIn.cshtml

@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "AssignmentTurnIn";
}

<!DOCTYPE html>

<h1> @Model.assignment.FirstOrDefault().Name </h1>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            background-color: #fff;
        }

            table th {
                background-color: #B8DBFD;
                color: #333;
                font-weight: bold;
            }

            table th, table td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            table, table table td {
                border: 0px solid #ccc;
            }
    </style>
</head>
<body>
    @using (Html.BeginForm("AssignmentTurnIn", "Students", new { classID = (Model.assignment.FirstOrDefault().ClassID), assignmentID = (Model.assignment.FirstOrDefault().AssignmentID) }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="file" name="postedFile" />
        <input type="submit" id="btnUpload" value="Upload" />
    }
    @using (Html.BeginForm("DownloadFile", "Students", FormMethod.Post))
    {
        <input type="hidden" id="hfFileId" name="FileId" />
        <input type="submit" id="btnDownload" value="Download" style="display:none" />
    }
    <hr />
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th style="width:50px">File ID</th>
            <th style="width:120px">File Name</th>
            <th style="width:80px">Download</th>
        </tr>
        @if (Model.documents.Count() > 0)
        {
            foreach (var file in Model.documents)
            {
                <tr>
                    <td>@file.Id</td>
                    <td>@file.Name</td>
                    <td><a href="javascript:;" onclick="DownloadFile(@file.Id)">Download</a></td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
        }
    </table>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript">
        function DownloadFile(fileId) {
            $("#hfFileId").val(fileId);
            $("#btnDownload")[0].click();
        };
    </script>
</body>
</html>

Oodle/Oodle/Views/Students/Grade.cshtml
@{
    ViewBag.Title = "Grade";
}

<center><h2>Grade View for Student Controller</h2></center>

Oodle/Oodle/Views/Students/Index.cshtml

@model Oodle.Models.ViewModels.TeacherVM

@{
    ViewBag.Title = "Index";
}

<div class="row fontClass">

    <h3>
        Your class page for: @Html.DisplayFor(Name => Model.cl.Name)
    </h3>

    <div class="container">
        <div>
            <div class="col-lg-6" id="teacherPage">
                <h3>Description</h3>
                <p style="font-size:14px;">
                    @Html.DisplayFor(Description => Model.cl.Description)
                </p>
            </div>
            <div class="col-sm-6" id="teacherPage">
                <h3> Notifications </h3>
                @foreach (var notif in Model.notifs)
                {
                    <p>
                        @Html.DisplayFor(Notification => notif.Notification)
                    </p>
                }
            </div>
        </div>
    </div>
    <hr class="style-four" />
    <hr class="style-four" />


</div>

Oodle/Oodle/Views/Students/Quiz.cshtml
@{
    ViewBag.Title = "Quiz";
}

<center><h2>Quiz View for Student Controller</h2></center>

Oodle/Oodle/Views/Students/Slack.cshtml
@{
    ViewBag.Title = "Slack";
}

<center><h2>Slack View for Student Controller</h2></center>

Oodle/Oodle/Views/Students/Task.cshtml
@{
    ViewBag.Title = "Task";
}

<center><h2>Task View for Student Controller</h2></center>